[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# HTML files - Cache corto para permitir actualizaciones rápidas
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"  # 1 minuto + revalidación

# Root index - Sin cache para asegurar actualizaciones inmediatas
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# CSS y JS - Cache corto con revalidación
[[headers]]
  for = "/src/css/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"  # 5 minutos + revalidación

[[headers]]
  for = "/src/js/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"  # 5 minutos + revalidación

# Service Worker - Sin cache
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Datos dinámicos - Cache muy corto
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"  # 1 minuto + revalidación

# QR codes - Cache moderado (pueden cambiar)
[[headers]]
  for = "/qrcodes/*"
  [headers.values]
    Cache-Control = "public, max-age=1800, must-revalidate"  # 30 minutos + revalidación

# Recursos estáticos (imágenes, audio) - Cache largo
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"  # 24 horas (solo para assets estáticos)

[[redirects]]
  from = "/invitacion"
  to = "/"
  status = 301

[[redirects]]
  from = "/invitacion/*"
  to = "/?id=:splat"
  status = 301 