[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300"  # Cache por 5 minutos

[[headers]]
  for = "/qrcodes/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"  # Cache por 1 hora

[[redirects]]
  from = "/invitacion"
  to = "/"
  status = 301

[[redirects]]
  from = "/invitacion/*"
  to = "/?id=:splat"
  status = 301 